### PR TITLE
Leaner, faster & stable

### PR DESCRIPTION
**Pull request by d4tocchini**
- [x] state persists in expected manner
  + _only tested on 2 concurrent peer connections in local network_
- [x] ensure messages missed while offline properly sync upon reconnect 
- [x] upgrade electron to `3.0.0-beta.10`
  + transitioned without hiccups but may need more thorough look for possible breaking API impacts
- [x] flatten production dep tree **only if and when `yarn install` instead of `npm`**
  + reduced `Cabal.app`'s `app.asar` from 54.6mb to 35.7mb 
  + dedup'd 46 packages, many of which included 3+ versions
  + general perf lift to be expected

Nice-to haves:

- modernize js lexicon - `const`, `let`, scrub out any glaring v8 deopts, aim for monomorphic, hope for constant time/memory, etc
- optimize build for perf wins in target chromium build, ie minimize penalty of lowest common denominator oriented webpack/babel.

### CODE REVIEW

**Comment by d4tocchini** [comment]
i kept running into state persistence issues, the same i've seen popping up in issues / comments -- cabals disappearing when restarting or when empty, not getting latest messages synced while offline, etc.  added these to top of list, hard to move forward without.

**Comment by nikolaiwarner** [comment]
@d4tocchini Great work here! Thanks!! This all looks good. Are you still hacking on this? I have a feeling some of the mysteriousness around syncing may be coming from cabal-core. I'm good to merge this as is though.

🎉🎉🎉

**Comment by d4tocchini** [comment]
i'll open other PR's if needed, go ahead and merge 🚀

**Comment by nikolaiwarner** [comment]
Yay! Thanks again!

**Pull request merged**
