### PR TITLE
Fix emoji picker

### PR DESCRIPTION
**Pull request by nikolaiwarner**

### CODE REVIEW

**Comment by cblgh** [comment]
😄 🎈

**Comment by todrobbins** [comment]
@nikolaiwarner: all good on the emoji picker fix expect that when I click in the search box the picker hides so that I can't actually search emoji

I was poking around your changes and think it might be related to `hideEmojiPicker`/`hideModals`

**Comment by cblgh** [comment]
ooh ooh ooh would it be possible to incorporate this somehow? https://github.com/cabal-club/commons/issues/2

so that emojis are interpreted from `:emoji-codes:` the issue ^ has some libraries

**Comment by cblgh** [comment]
looks like it's (maaaaybe?) possible from the dep we're using for the emojipicker in desktop!

see `:colons:` in https://github.com/missive/emoji-mart#examples-of-emoji-object

**Comment by nikolaiwarner** [comment]
nice catch @todrobbins ! fixed it!

**Comment by nikolaiwarner** [comment]
@cblgh ah when the :emoji-code: is rendered in the message list it should appear as the emoji?

**Comment by cblgh** [comment]
@nikolaiwarner yeah! just use the :emoji code: in the text, that way they'll appear in cli as well

**Pull request merged**
