### PR TITLE
[WIP] File attachments

### PR DESCRIPTION
**Pull request by nikolaiwarner**
image

For those interesting in helping me test this out, please check out this branch and post some file messages to this cabal and let me know how it goes in the PR comments: 
cabal://08c6eb4ead7dc162ec5a68102cf056bd5b457a64e92d008af2f4126134026dee

How to use: drag and drop a file into the app and it will share that file via dat. If it's an image, it'll show it inline.

At the moment in this branch, there's no toggles or ui exposed for adjusting options. If there's an attachment in a message, the client will fetch it. 

Also, let me know what ideas you have for UX!

### CODE REVIEW

**Comment by cblgh** [comment]
woahhhhh @nikolaiwarner this is great, fantastic implementation! let me know if sync works for you

i'll try to keep my laptop awake all day 
Screen Shot 2019-08-04 at 11 56 09

**Comment by dwblair** [comment]
Amaaaaaaazing @nikolaiwarner !  

I put up a photo of mushrooms because I think you like mushrooms? 

And for @cblgh, I put up a photo I found of a spectacular mushroom in the city of Malmö.

files

The cabal doesn't seem to have peered yet with either of you (only been a few minutes and maybe you're both offline) ... but the file drag-and-drop was super slick and nice!

Also really lovely to have the "Dat Link" and "Local File" links!  "Local File" seems to work ... "Dat Link" not yet, right?

Also wonder if it might make sense to have the Dat URL and Local File Links display their locations / URLS when hovering over them?  E.g. when I click on "Local File" in Ubuntu it pops up the file in my image viewer but (and this may just be Ubuntu weirdness) it doesn't tell me where exactly the file lives.

SO. SLICK.  Bless you.

And @cblgh thanks for all your work, too, on the lower-level goodness that makes all of this possible. 

Cheers!

**Comment by dwblair** [comment]
Update!  Was able to connect with @cblgh -- wahoo!  

So this is what I see after he connected:

updates

When I click on the link for "Local File" in Ubuntu, I get:

failedtoget

Sooooo tantalizingly close!

**Comment by cblgh** [comment]
yup! same as don above

buut the dat links for my images load perfectly in beaker! (still can't see his, in cabal desktop or beaker. i'm guessing we can't connect our dat archives somehow)

**Comment by dwblair** [comment]
Update ... so, for example, the error dialog I get when I click on a link says:

> Failed to open "/home/dwblair/.cabal-desktop/v1/files/08c6eb4ead7dc162ec5a68102cf056bd5b457a64e92d008af2f4126134026dee/8e0d49da37c802cf3a2735e6d859d96ac60055c99282f9f1d1d31a30a6b6d5b3/e28218d879b0fc9a1320046d8280fa412731d11e60cadd39cc4f954779a80a25/Screen Shot 2019-05-20 at 09.46.56.png".

> Error when getting information for file “/home/dwblair/.cabal-desktop/v1/files/08c6eb4ead7dc162ec5a68102cf056bd5b457a64e92d008af2f4126134026dee/8e0d49da37c802cf3a2735e6d859d96ac60055c99282f9f1d1d31a30a6b6d5b3/e28218d879b0fc9a1320046d8280fa412731d11e60cadd39cc4f954779a80a25/Screen Shot 2019-05-20 at 09.46.56.png”: No such file or directory.

Then, when I look into my local directory structure, I see:

update

I.e., there seems to be a missing dat archive (I think?) in the 8e0d49da37c802cf3a2735e6d859d96ac60055c99282f9f1d1d31a30a6b6d5b3 directory, which should be ''e28218d879b0fc9a1320046d8280fa412731d11e60cadd39cc4f954779a80a25' ... 

But there is a ".dat" subdirectory in that directory ... so it looks like dat is working for me somewhat!  Maybe just not syncing quite yet? Or something?

**Comment by todrobbins** [comment]
@nikolaiwarner, I'm still in the midst of testing, but we should probably enable right-click support for all of those hyperlinks in case folks want to copy/paste/share the link with others.

**Comment by RangerMauve** [comment]
OMG THIS IS SO COOL!!

**Comment by todrobbins** [comment]
Have any of my messages come through for any of you?

Screen Shot 2019-08-05 at 11 43 59 AM

I tried a variety of filetypes/file sizes. They're mostly in `#test3`.

**Comment by todrobbins** [comment]
Dat creation looks good on my end, and the dat/local file links work great:

files

Anyone able to load this dat in Beaker? `dat://4b13eab04b37c68bf08f47bf8b2625749d1ec3537d3b0f92a28e3acb5c77572c/`

**Comment by RangerMauve** [comment]
Just loaded your archive in Beaker. 😁

**Comment by todrobbins** [comment]
@RangerMauve could you see any of my messages in the cabal or just load my dat from that link?

**Comment by dwblair** [comment]
Hi @todrobbins !  Sorry this is rushed, but: I had the same experience with your images as with those of @cblgh and @nikolaiwarner -- I get little "broken image links" in lieu of your images, and the same error messages when I click on the image hyperlink.  My own uploads work fine locally, though!

@todrobbins -- are you able to load images from peers? 

Cheers all!

**Comment by todrobbins** [comment]
@dwblair I'm not able to load images from peers. I see some file link messages but none of the dat links resolve:

Screen Shot 2019-08-05 at 9 35 25 PM

**Comment by nikolaiwarner** [comment]
Thanks everyone for helping to test this experiment out last fall! We'll make file sharing happen eventually!

**Pull request closed without merging**
