### PR TITLE
Update to cabal-core 9

### PR DESCRIPTION
**Pull request by nikolaiwarner**

### CODE REVIEW

**Comment by cblgh** [comment]
@nikolaiwarner nice!

can you double check the `node_modules` to see which cabal-core version you have installed?

`npm ls cabal-core` in the cabal-desktop folder should do it. (i'm weirded out by why i could see your messages when you ran desktop@cabal-core@9.0)

**Comment by nikolaiwarner** [comment]
@cblgh ya this is def on core@9

my guess is what we saw was me sending that message on core@9 then later switching to another branch that was using core@7 and then syncing

**Comment by cblgh** [comment]
@nikolaiwarner ahh yes of course, that makes abundant sense!

**Comment by cblgh** [comment]
@nikolaiwarner feel free to merge & do your distribution building magic :~

**Comment by cblgh** [comment]
also just adding some hearts for appreciation

🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤 🖤

**Comment by cblgh** [comment]
🎉

**Pull request merged**
