### PR TITLE
add, list, store multiple cabals

### PR DESCRIPTION
**Pull request by karissa**
this means that if you already joined a channel when you open desktop the next time you will automatically join the last one you were in.

### CODE REVIEW

**Comment by noffle** [comment]
aw yeah :heart:

**Comment by nikolaiwarner** [comment]
I'm going to attempt to finish this one ... @karissa let me know if I shouldn't 😸

**Comment by karissa** [comment]
please do @nikolaiwarner !

**Comment by simbolo** [comment]
Hey, please let me know if I can help with anything UI related! 👍

**Comment by cblgh** [comment]
cc @nikolaiwarner what's the status on this? :3

**Comment by nikolaiwarner** [comment]
OK! it's ready sorry for the delay :D .... 👶 🍼 you know..

**Comment by nikolaiwarner** [comment]
image

**Comment by cblgh** [comment]
ooopf THIS IS SO GOOOOOD

**Comment by nikolaiwarner** [comment]
This was mostly @karissa! I just carried the baton across the finish line 🏃‍♀️

**Pull request merged**
