### PR TITLE
Visual adjustments

### PR DESCRIPTION
**Pull request by simbolo**
Visual adjustments + proposals to the UI theme (Work in progress)

### CODE REVIEW

**Comment by noffle** [comment]
Could you describe what you're changing? Lemme know when you're ready to merge. :tada:

**Comment by simbolo** [comment]
The UI mostly, tried to clean up the CSS a bit, still needs work.

screen shot 2018-08-06 at 10 08 29 pm

**Comment by noffle** [comment]
Wow, this is looking *slick*!

**Comment by simbolo** [comment]
Sure thing

screen shot 2018-08-07 at 12 22 32 am

**Comment by simbolo** [comment]
Yeah, go ahead :)

**Pull request merged**
