### PR TITLE
Add link tooltip

### LINKED ISSUE #295: Show real link target on hover
Someone with malicous intents might write something like: `[http://very-good-website.org](http://very-bad-website.org)`. This gets shown as: [http://very-good-website.org](http://very-bad-website.org). As far as I can tell dragging the link is the only way to find out that the link actually leads to a malicous website. One way to solve this might be showing some kind of tooltip with the real target of the link.

### PR DESCRIPTION
**Pull request by sylvainDNS**
I made a little PR to resolve #295 

I was inspired by a famous app to style it!

It's the first time that I use React portal, feel free to give a review :wink:

### CODE REVIEW

**Comment by cblgh** [comment]
thanks @sylvainDNS! would you mind including a screenshot of how it looks? helps a lot with managing visual-style PRs :)

**Comment by khubo** [comment]
@sylvainDNS Thanks  for the PR!! 
I am confused about the need for `portals` though.

**Comment by sylvainDNS** [comment]
Hi! Here is the final render
image

I will try to manage it without portals. Do yo squash commit during merge, or do you prefer that I push force on my own branch to keep a clean git history ?

**Comment by khubo** [comment]
@sylvainDNS  cool, that would be lovely! Regarding the commits, you can squash them if you want to.

**Comment by sylvainDNS** [comment]
It's ok for me.
There may be a better way to position the tooltip (with CSS only), but I didn't succeed.

**Comment by khubo** [comment]
@sylvainDNS i have pulled the PR and tested locally, the positioning seems fine to me :+1:

**Comment by cblgh** [comment]
@khubo let's merge whenever you say it's good :)

thanks again for this @sylvainDNS!

**Review by khubo — APPROVED** [review]

**Pull request merged**
