### PR TITLE
 Add a profile panel for showing information and actions about another peer

### PR DESCRIPTION
**Pull request by nikolaiwarner**
This is a panel that can show information and actions for another peer such as:
- moderation actions
- viewing status message
- message history
- moderation history
- starting a direct message
- starting a call
- etc!

### CODE REVIEW

**Comment by cblgh** [comment]
niiiiiiiiiiiice

**Comment by cblgh** [comment]
@nikolaiwarner d'ya think that _x-to-close_ functionality could be ferried over to the _users-in-channel_ listing? i was always a bit confused at how to close that

**Comment by nikolaiwarner** [comment]
@cblgh yeah! i'm thinking that panel will soon transform into a "channel details" panel

**Comment by cblgh** [comment]
très bien!

**Pull request merged**
