### PR TITLE
Switch to cabal-client

### PR DESCRIPTION
**Pull request by nikolaiwarner**
This is a big change that integrates the cabal-client lib with Cabal Desktop. This lets us rely on all the great features provided by that and cleans up as much redundant code as possible.

I'll use this PR to track testing and fixing issues with this change and coordinate additional collaboration with pushing it forward. ❤️

Todo:
- [x] @nikolaiwarner: fix system messages
- [x] @nikolaiwarner: channel browser styling
- [x] @nikolaiwarner: default/last used channel not set initially
- [x] @nikolaiwarner: fix topics ui
- [x] @khubo posting a message should go to the correct channel, not always `default`
- [x] @khubo update channel list on new channel added
- [x] @khubo: changing channels makes the channel list break
- [x] @khubo cabal automatically get switched
- [x] @nikolaiwarner: set nick from /nick - possibly fix other slash commands
- [x] fix unread counts/indicators/notifications
- [ ] possible issue with settings not persisting between reloads

### CODE REVIEW

**Comment by cblgh** [comment]
🤗

**Comment by nikolaiwarner** [comment]
@khubo If you're interested in helping solve some of the issues from the todo list up there let me know! <3 <3

**Comment by todrobbins** [comment]
I done screwed up with an unintended merge commit. I don't know how to revert it. @nikolaiwarner can you advise?

**Comment by nikolaiwarner** [comment]
@todrobbins lol

**Comment by todrobbins** [comment]
Thank you all for your patience and for letting me learn along the way ❤️

**Comment by nikolaiwarner** [comment]
@todrobbins we're making it happen together! 🤗 🤗  thanks for being a part of the team!

**Comment by cblgh** [comment]
[heeeeeeeeeeeey ya, heeeeeey yaa](https://youtu.be/PWgvGjAhvIw?t=101)

**Comment by nikolaiwarner** [comment]
For those following along, here's where the new channel browser style is headed:

image

**Comment by khubo** [comment]
closes #198

**Comment by nikolaiwarner** [comment]
Ok, this branch is ready for some testing. If anyone would like to try out this branch and give some feedback, this is a great time to do it! Thanks everyone!

**Comment by cblgh** [comment]
AIIIIIIIIIIIIGHT! super excited @khubo & @nikolaiwarner

**Comment by khubo** [comment]
finally! excited

**Pull request merged**
