### PR TITLE
add keyboard shortcuts for cabal navigation

### LINKED ISSUE #149: Add key combos for navigating between cabals
In addition to navigating between channels (thanks @nikolaiwarner!), we could add `cmd/ctrl+1`, `cmd/ctrl+2`, `cmd/ctrl+3`, etc... for selecting cabal's along the sidebar, this might also benefit from addressing/implementing suggestions in #64.

### PR DESCRIPTION
**Pull request by khubo**
closes #149

### CODE REVIEW

**Comment by nikolaiwarner** [comment]
👏👏👏 this is great @khubo! 

could the command to jump cabals be cmd/ctrl-number instead of cmd/ctrl-shift-number?
so just like: `⌘-1` ?

**Comment by khubo** [comment]
@nikolaiwarner what about next and previous? do you think `ctrl+shift+(n/p)` would be a better idea?

**Comment by nikolaiwarner** [comment]
@khubo yes! i like `ctrl+shift+(n/p)`

**Comment by khubo** [comment]
@nikolaiwarner modified it.. also, refactored the code a bit.

**Comment by nikolaiwarner** [comment]
@khubo nice! could the jump index start at 1 instead of 0?

also when one nexts past the last cabal should it loop back to the first cabal? (and likewise for previous)

**Comment by khubo** [comment]
@nikolaiwarner good idea.. updated the code for the same.

**Comment by nikolaiwarner** [comment]
Thanks @khubo! Works great!! 🔥🔥🔥🔥🔥🔥🔥

oh on the index thing, i know what you mean! :D ... but i expect people to think of the first cabal on the list being number 1 and so on.

**Pull request merged**
