### PR TITLE
Cabal ui refresh

### PR DESCRIPTION
**Pull request by nikolaiwarner**
Implementation of the ui refresh from @simbolo 's styles from #28 

screen shot 2018-08-14 at 1 39 03 pm

### CODE REVIEW

**Comment by noffle** [comment]
Runs really well on my linux machine. Anyone else want to give it a look over before I merge?

cc @cblgh @staltz @ralphtheninja 

@nikolaiwarner could you set the root dir `screenshot.png` to the image you've attached here as well?

**Comment by nikolaiwarner** [comment]
Overall, the start/new cabal screen still needs some design love and I really need to get some app icons on this thing. Probably should make new issues for those.

**Comment by fwip** [comment]
Looks pretty good on my macbook. :)

The one weirdness that I see is that long strings don't line break, instead you get a horizontal scroll bar across the bottom of the window. Screenshots here: https://imgur.com/a/s3VxIYY

**Comment by nsantini** [comment]
Just testing it on macOS, all looking smooth here. I don't get the long string issue mentioned by @fwip , have you run "npm install; npm build" after checking out the branch?

**Comment by noffle** [comment]
Thank you @fwip @nsantini for testing! Merging.

**Comment by cblgh** [comment]
🔥 🔥 🔥 this is so gooooooooood @simbolo and @nikolaiwarner y'all are the desktop dreamteam

**Pull request merged**
