### PR TITLE
Travis fix

### PR DESCRIPTION
**Pull request by karissa**

### CODE REVIEW

**Comment by noffle** [comment]
It's complaining about

```
Error: Please specify author 'email' in the application package.json
```

https://travis-ci.org/cabal-club/cabal-desktop/jobs/539456917#L1897

**Comment by karissa** [comment]
thx @noffle !

**Comment by cblgh** [comment]
woah nice! looks like it's only windows that's failing (and after 30s? wtf)

anyone have a clue what that's about? like, should we just remove windows from the autobuilds, or do we just need to tweak something tiny to get it running

**Comment by nikolaiwarner** [comment]
Screen Shot 2019-07-13 at 6 36 21 PM

🤷‍♀️

**Pull request merged**
