### PR TITLE
fix breaking channel list.

### PR DESCRIPTION
**Pull request by khubo**
@nikolaiwarner  this should fix the breaking of channels. 
Also, channel list is being sorted

### CODE REVIEW

**Comment by cblgh** [comment]
🖤 🖤 🖤

**Comment by nikolaiwarner** [comment]
💯💯💯 looks great @khubo! i'm a dummy and just rebased `use-cabal-client` from master so could you rebase this from `use-cabal-client`? then we can merge

**Comment by khubo** [comment]
> 100100100 looks great @khubo! i'm a dummy and just rebased `use-cabal-client` from master so could you rebase this from `use-cabal-client`? then we can merge

will update soon!

**Comment by nikolaiwarner** [comment]
🔥🔥🔥🔥

**Comment by nikolaiwarner** [comment]
I can confirm this solves a few things :D

**Pull request merged**
