### PR TITLE
Switch cabal

### PR DESCRIPTION
**Pull request by khubo**
- adds [optional chaining](https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining)  syntax via babel.
- sets nick and switches cabal while creating a new one.

### CODE REVIEW

**Comment by nikolaiwarner** [comment]
nice! @khubo i made a little change so that it goes to the default channel when making a new cabal instead of the !status channel.

what do you think of using another term for the default nickname? maybe something less menacing and more friendly like "Peer" or "Friend"?

**Comment by khubo** [comment]
@nikolaiwarner thats cool. What about "comrade"? jk.. maybe lets use a library to generate random names [ex](https://www.npmjs.com/package/unique-names-generator) or maybe pokemon names :D.. so there are no multiple people with same names.

**Comment by cblgh** [comment]
haha yeah i agree that conspirator can be a bit out there, especially when demoing. but i think the `a e s t h e t i c` should be maintained.

if we were to use random names how about combining these two lists 
as `<noun>-<adjective>`: 

_nouns_
> lichen
> moss
> shadow
> stone
> ghost
> friend
> spore
> fungi
> mold

_adjectives_
> ancient
> whispering
> hidden
> emerald
> occult
> obscure
> wandering
> ephemeral
> eccentric

`ephemeral-moss`, `eccentric-stone`, `occult-lichen` etc. and then using the public key string-encoding as the seed to randomly pick from the two lists

**Comment by nikolaiwarner** [comment]
@cblgh oh i love that. added! 

@khubo great job with this as usual! gonna merge

**Pull request merged**
