### PR TITLE
[draft] show members in channel

### LINKED ISSUE #203: Add a UI to list channel members
This probably could be a pane that opens from the right, listing each member who has joined the active channel and showing if they are online.

bonus: since it's not relevant on the channel level, move the peer connected count to the sidebar on the the peer list

from here:
image
to here:
image

### PR DESCRIPTION
**Pull request by khubo**
fixes #203 
@nikolaiwarner  this is a very crude fix  - no proper css at all.. I would really love some feedback on how about ui regarding this.

channelmember

### CODE REVIEW

**Comment by cblgh** [comment]
looks dope, maybe we can replace the `Toggle Member List` using a discrete con representing the member count:
image
hex for the color btw is #B497E7

**Comment by nikolaiwarner** [comment]
@khubo this is great!!!

i second @cblgh's suggestion for the people icon along with the count for the toggle button. i'd be ok dropping the "share cabal" button while we're at it. we dont need heavy buttons up there since they're not used often

minor things:
- left align the name rows with the "Channel Members" title
- maybe make all the names #000 so they're easier to see
- disable the hover effect and cursor as pointer since these rows arent clickable yet
- also there's an overflow issue with scrolling when the list is longer than the window

**Comment by khubo** [comment]
@cblgh @nikolaiwarner updated
updateSidebar

**Comment by khubo** [comment]
I have swapped the position of ellipsis and members ^_^

**Comment by nikolaiwarner** [comment]
@khubo very nice!! i think the button could use a little more visual fine tuning but this works for now! great job!

**Pull request merged**
