### PR TITLE
Add setting to toggle desktop notifications

### LINKED ISSUE #71: Move desktop notifications to a opt-in cabal setting
Desktop notifications in cabal are still an experimental feature. Let's disable them by default and allow user to opt in to the feature from the cabal-specific settings screen.

Currently blocked by not having a settings interface. :D

### PR DESCRIPTION
**Pull request by nikolaiwarner**
desktop notifications will now be disabled by default. Users may opt in to notifications from the cabal settings screen.

fixes #71

Screen Shot 2019-07-13 at 11 50 05 PM

### CODE REVIEW

**Comment by cinnamon-bun** [comment]
Hooray!  Nice to have a settings screen now

**Comment by cblgh** [comment]
oh yay so fast!

**Comment by nikolaiwarner** [comment]
@todrobbins nice! soooo i'm kinda waiting for cabal-client to land and implement that first 😛

**Comment by todrobbins** [comment]
Makes sense!

**Comment by cblgh** [comment]
@nikolaiwarner yeah i think that's a good decision too!

**Pull request merged**
