### PR TITLE
add channel select modal

### PR DESCRIPTION
**Pull request by khubo**

### CODE REVIEW

**Comment by khubo** [comment]
@nikolaiwarner aesthetically the modal looks terrible. plis let me know what will look better :smile_cat:

**Comment by cblgh** [comment]
@khubo wanna include a screenshot for aesthetic changes? :) lets people, like me!, give feedback without needing to pull in the latest wip changes and build stuff 🖤

**Comment by khubo** [comment]
@cblgh haha.. here you go! 
cabal
Screenshot from 2020-01-20 16 36 15

**Comment by nikolaiwarner** [comment]
Ideally, I'd like to have a larger interface for looking at channels so that we can show the user extra info about each channel before they dive in. For example this is what Slack does in their channel browser: 

image

In our case, we can include the number of people who have joined the channel, the topic, and additional ui for immediately joining, viewing but not joining, etc... so people can be better informed about the channel before committing.... and also an option to create a new channel.

This is what I was going toward in the ChannelBrowserContainer component but it just needed some better styling.... which i was about to do today :D 

@khubo What do you think?

**Comment by khubo** [comment]
@nikolaiwarner yep, I think, that one looks better. There is much more info in it.

**Comment by nikolaiwarner** [comment]
Thanks for understanding! I'll wrap up what i was planning for this and show you. I think after this and fixing unread message counts (which you're welcome to take a look at), we can get the cabal-client branch into master and have folx test it out!!

**btw @khubo I am sooo thankful for your help lately! 🤗 super appreciated!!**

**Comment by khubo** [comment]
@nikolaiwarner i will take a look into unread count tommorow, if u havent started on it. Deleting channel is also on my list. That should be a quick one tho.

**Comment by nikolaiwarner** [comment]
@khubo awesome! 

In cabal you cant actually delete a channel but you can unjoin a channel so it doesnt appear in your channel list. I've added a button at the top so one can "leave" a channel and unjoin. I dont think it's the best UX... we dont really need to show that all the time... but it's just where I've placed it for the moment:

image


Maybe someday we make an options menu or screen for channels to give this button a home similar to how Slack handles this:
image

**Comment by khubo** [comment]
@nikolaiwarner oops.. i think i used the wrong terminology. I was referring to the [same](https://github.com/cabal-club/cabal-client/blob/master/api.md#CabalDetails+leaveChannel).

**Comment by todrobbins** [comment]
Nice work, @khubo!

**Pull request closed without merging**
