### PR TITLE
Move darkmode settings to View menu

### LINKED ISSUE #290: Change in dark mode enable option
As of now `dark mode` is set at cabal level. Wouldn't it better to move it under "view" menu and make it an app level option?

### PR DESCRIPTION
**Pull request by khubo**
closes #290

### CODE REVIEW

**Comment by nikolaiwarner** [comment]
fantastic job @khubo! this is great! 🖤 🖤 🖤 🖤

**Comment by nikolaiwarner** [comment]
Hi @khubo! Sorry for taking forever to properly review this. It works great! Could we have dark mode enabled by default?

**Comment by khubo** [comment]
@nikolaiwarner sure, willl update the pr soon!

**Comment by khubo** [comment]
@nikolaiwarner updated the PR!

**Comment by nikolaiwarner** [comment]
nice! i'm going to test drive this a bit and then make a new release! thanks @khubo!

**Comment by cblgh** [comment]
🎉

**Pull request merged**
