### PR TITLE
Use frameless window on MacOS.

### PR DESCRIPTION
**Pull request by Gronis**
Not a necessity, but a slightly more clean look and feel on MacOS.

If another os is used, the interface looks the same as before. 
You can still move the window around easily by dragging around in the upper right area between the "star" and the "dots".

### CODE REVIEW

**Comment by nikolaiwarner** [comment]
@Gronis I'm good with this change for MacOS. thanks again!

How do other MacOS users feel about this? @cblgh @khubo

**Comment by Gronis** [comment]
I really like the initiative that is cabal chat! Thanks for reviewing PR's so fast :)

**Comment by khubo** [comment]
looks neat!

**Review by khubo — APPROVED** [review]

**Comment by nikolaiwarner** [comment]
@Gronis thanks again! you've joined us at a fun time too! @khubo and i are working on a big rewrite of the desktop client which we'll use in cabal-web (and potentially cabal-mobile). so there's lots of fun things to make :D

**Pull request merged**
