### PR TITLE
feat: Add new message indicator to cabals list

### PR DESCRIPTION
**Pull request by nikolaiwarner**
also Added new message indicator badge to application icon (MacOS only)

Screen Shot 2019-07-23 at 10 20 39 AM
Screen Shot 2019-07-23 at 10 20 20 AM

### CODE REVIEW

**Comment by dwblair** [comment]
So useful!

And wait woahhh is that the new application icon? It’s sliiiiiick!

**Comment by todrobbins** [comment]
Testing this now, and I'm running into a weird bug where my own messages to a channel are coming through as notifications (macOS) and as indicators within the app:

Screen Shot 2019-07-23 at 9 48 24 AM

Screen Shot 2019-07-23 at 9 48 43 AM

**Comment by todrobbins** [comment]
Also, the app icon isn't updating after I'm read the new messages:

Screen Shot 2019-07-23 at 9 54 27 AM

**Comment by nikolaiwarner** [comment]
ok @todrobbins want to take it for another spin?

**Comment by nikolaiwarner** [comment]
good idea @todrobbins! added it!

**Pull request merged**
